"""empty message

Revision ID: b803d6ed7db1
Revises: 7b894978689b
Create Date: 2022-01-06 20:43:28.773645

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b803d6ed7db1'
down_revision = '7b894978689b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_playlist_uri'), 'playlist', ['uri'], unique=False)
    op.add_column('score', sa.Column('date', sa.DateTime(), nullable=True))
    op.create_index(op.f('ix_score_date'), 'score', ['date'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_score_date'), table_name='score')
    op.drop_column('score', 'date')
    op.drop_index(op.f('ix_playlist_uri'), table_name='playlist')
    # ### end Alembic commands ###
